// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFekMQQ2j5u5N0O-BXTYvLjZ8tikyVr6Y',
    appId: '1:247511531096:web:bbabd35879b708c107542d',
    messagingSenderId: '247511531096',
    projectId: 'school-kid-tracking-c1930',
    authDomain: 'school-kid-tracking-c1930.firebaseapp.com',
    storageBucket: 'school-kid-tracking-c1930.firebasestorage.app',
    measurementId: 'G-RBLEH9TGME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAib03vkuFR_56mSCL6dvtddTiSA7rFJB0',
    appId: '1:247511531096:android:54085997369e5fb007542d',
    messagingSenderId: '247511531096',
    projectId: 'school-kid-tracking-c1930',
    storageBucket: 'school-kid-tracking-c1930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyS4w7kb2ZJ-7e2LZEHSbACndvqgg2Eg',
    appId: '1:247511531096:ios:cde242de2617e0d707542d',
    messagingSenderId: '247511531096',
    projectId: 'school-kid-tracking-c1930',
    storageBucket: 'school-kid-tracking-c1930.firebasestorage.app',
    iosBundleId: 'com.example.schoolKidTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyyS4w7kb2ZJ-7e2LZEHSbACndvqgg2Eg',
    appId: '1:247511531096:ios:cde242de2617e0d707542d',
    messagingSenderId: '247511531096',
    projectId: 'school-kid-tracking-c1930',
    storageBucket: 'school-kid-tracking-c1930.firebasestorage.app',
    iosBundleId: 'com.example.schoolKidTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFekMQQ2j5u5N0O-BXTYvLjZ8tikyVr6Y',
    appId: '1:247511531096:web:6609a356ec72ded107542d',
    messagingSenderId: '247511531096',
    projectId: 'school-kid-tracking-c1930',
    authDomain: 'school-kid-tracking-c1930.firebaseapp.com',
    storageBucket: 'school-kid-tracking-c1930.firebasestorage.app',
    measurementId: 'G-R6MSVENJ11',
  );
}
